/******************************************************************************
* File Name:   secure_boot_config.c
*
* Description: This is the source code for Secure boot configuration of CM0+ core
*              for ModusToolbox.
*
* Related Document: See README.md
*
*
*******************************************************************************
* $ Copyright 2026-YEAR Infineon Technologies AG $
*******************************************************************************/

/*******************************************************************************
* Header Files
*******************************************************************************/
#include "cy_pdl.h"
#include "cy_si_config.h"
#include "cy_si_keystorage.h"

/*******************************************************************************
* Macros
********************************************************************************/
/* App version */
#define SI_VERSION_MAJOR        (0UL) /* Major version */
#define SI_VERSION_MINOR        (0UL) /* Minor version */

/* Flashboot parameters */
#define CY_SI_FLASHBOOT_FLAGS   ((CY_SI_FLASHBOOT_CLK_50MHZ << CY_SI_TOC_FLAGS_CLOCKS_POS) \
                                | (CY_SI_FLASHBOOT_WAIT_20MS << CY_SI_TOC_FLAGS_DELAY_POS) \
                                | (CY_SI_FLASHBOOT_SWJ_ENABLE << CY_SI_TOC_FLAGS_SWJEN_POS) \
                                | (CY_SI_FLASHBOOT_VALIDATE_ENABLE << CY_SI_TOC_FLAGS_APP_VERIFY_POS) \
                                | (CY_SI_FLASHBOOT_FBLOADER_ENABLE << CY_SI_TOC_FLAGS_FBLOADER_ENABLE_POS))

/* The start address of secure image */
#define SI_ADDR                 ((uint32_t)__si_addr_linker_symbol)

/* Secure image size */
#define SI_SIZE                 ((uint32_t)__si_size_linker_symbol)

/* Vector table offset */
#define SI_VECTOR_OFFSET        ((uint32_t)__si_vector_offset_linker_symbol)

/* CM0+ VT Offset */
#define SI_VT_OFFSET            (SI_VECTOR_OFFSET) - offsetof(cy_stc_si_appheader_t, core0Vt)

/* CM0+ ARM CPUID[15:4] Reg shifted to [31:20] */
#define SI_CPUID                (0xC6000000UL)

/* Index ID of the CM0+ core */
#define SI_CORE_IDX             (0UL)

/*******************************************************************************
* Global Variables
********************************************************************************/
/* Location info provided from linker */
extern const char __si_addr_linker_symbol[];
extern const char __si_size_linker_symbol[];
extern const char __si_vector_offset_linker_symbol[];

/*******************************************************************************
* TOC2 in SFlash
*
* NOTE: Public key (cy_publicKey in secure_boot_key.c file) also in SFlash, 
* and it generated by tool, do not modify this file.
********************************************************************************/
CY_SECTION(".cy_toc_part2") __USED static const cy_stc_si_toc_t cy_toc2 =
{
    .objSize        = CY_SI_TOC2_OBJECTSIZE,    /* Object Size (Bytes) excluding CRC */
    .magicNum       = CY_SI_TOC2_MAGICNUMBER,   /* TOC2 ID (magic number) */
    .smifCfgAddr    = 0UL,                      /* SMIF config list pointer */
    .appAddr1       = SI_ADDR,                  /* App1 (CM0+ First User App Object) addr */
    .appFormat1     = CY_SI_APP_FORMAT_CYPRESS, /* App1 Format */
    .appAddr2       = 0UL,                      /* App2 addr: not used */
    .appFormat2     = CY_SI_APP_FORMAT_BASIC,   /* App2 Format */
    .cmx1appAddr1   = 0UL,                      /* App3 (CMx_1 1st User App Object) addr */
    .cmx1appAddr2   = 0UL,                      /* App4 (CMx_1 2nd User App Object) addr */
    .cmx2appAddr1   = 0UL,                      /* App5 (CMx_2 1st User App Object) addr */
    .cmx2appAddr2   = 0UL,                      /* App6 (CMx_2 2nd User App Object) addr */
    .reserved1      = {0UL},                    /* Reserved */
    .securityUpdateMaker = 0UL,                 /* Marker for Security Updates: disable PPUs configuration */
    .shashObj       = 3UL,                      /* Number of verified additional objects (S-HASH)*/
    .sigKeyAddr     = CY_SI_PUBLIC_KEY,         /* Addr of signature verification key */
    .appProtectionAddr = CY_SI_SWPU_BEGIN,      /* Addr of SWPU Objects */
    .reserved2      = {0UL},                    /* Reserved */
    .tocRevision    = 0UL,                      /* TOC2 Revision */
    .tocFlags       = CY_SI_FLASHBOOT_FLAGS,    /* Flashboot flags stored in TOC2 */
};

/*******************************************************************************
* Application header of CM0P APP in Code Flash
********************************************************************************/
/* Secure Application header for the CodeFlash application */
CY_SECTION(".cy_app_header") __USED static const cy_stc_si_appheader_t cy_si_appHeader = 
{
    .objSize        = SI_SIZE,
    .appId          = (SI_APP_VERSION(SI_VERSION_MAJOR, SI_VERSION_MINOR) | CY_SI_APP_ID_SECUREIMG),
    .appAttributes  = 0UL,                      /* Reserved */
    .numCores       = 1UL,                      /* Only CM0+ */
    .core0Vt        = SI_VT_OFFSET,             /* CM0+ VT offset */
    .core0Id        = SI_CPUID | SI_CORE_IDX,   /* CM0+ core ID */
};

/*******************************************************************************
* Application digital signature of CM0P APP in Code Flash
********************************************************************************/
/* Secure Image Digital signature (Populated by cymcuelftool) */
CY_SECTION(".cy_app_signature") __USED CY_ALIGN(4) 
static const uint8_t cy_si_appSignature[CY_SI_SECURE_DIGSIG_SIZE] = {0u};


/*******************************************************************************
* Function Prototypes
********************************************************************************/


/* [] END OF FILE */
